jdbc:
  jdbc.driver: com.mysql.jdbc.Driver
  jdbc.url=jdbc: mysql://localhost:3306/springboot
  jdbc.username: root
  jdbc.password: root

#多个yml 联合使用
spring:
  profiles:
    active: one,two

#tomcat 端口
server:
  port: 80