jdbc:
  jdbc.driver: com.mysql.jdbc.Driver
  jdbc.url=jdbc: mysql://localhost:3306/springboot
  jdbc.username: root
  jdbc.password: root

#多个yml 联合使用
spring:
  profiles:
    active: one,two
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot
    username: root
    password: root

#tomcat 端口
server:
  port: 80

#日志记录级别
logging:
  level:
    com.mic: debug
    org.springframework: info